version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.535-jdk21
    container_name: jenkins
    restart: always
    ports:
      - "80:8080"
      - "50000:50000"
      - "8082:8082"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - DOCKER_GID=110
    group_add:
      - 110

  ansible-agent:
    build: ./jenkins-agent-ansible
    container_name: jenkins-ansible
    restart: always
    environment:
      - JENKINS_URL=http://jenkins:8080/
      - JENKINS_AGENT_NAME=ansible-agent
      - JENKINS_SECRET=JENKINS_SECRET
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    depends_on:
      - jenkins

volumes:
  jenkins_home:
