#init-k8s-master.yml
---
- name: Prepare and configure Kubernetes master node
  hosts: k8s_master
  become: yes
  gather_facts: no

  tasks:

    - name: Wait 300 seconds for SSH connection
      wait_for_connection:
       timeout: 300

    # Установка зависимостей и обновление
    - name: Update apt and install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: yes
        state: present

    - name: Disable SWAP
      shell: swapoff -a
      ignore_errors: yes

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    # Настраиваем сетевые параметры ядра
    - name: Load kernel modules
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Ensure modules loaded
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl params
      command: sysctl --system

    # Устанавливаем containerd
    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Restart and enable containerd
      systemd:
        name: containerd
        enabled: true
        state: restarted

    # Устанавливаем Kubernetes пакеты
    - name: Add Kubernetes apt key
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_replace('\.[0-9]+$', '') }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_replace('\.[0-9]+$', '') }}/deb/ /

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        update_cache: yes
        state: present

    - name: Hold kube* packages to prevent auto-updates
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Copy Nexus cert from Jenkins to worker
      copy:
        src: "{{ nexus_cert_file }}"
        dest: /usr/local/share/ca-certificates/nexus.crt
        owner: root
        group: root
        mode: 0644

    - name: Update CA certificates
      command: update-ca-certificates

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: true

    - name: Initialize Kubernetes master node
      command: >
        kubeadm init
        --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create kube config for root
      shell: |
        mkdir -p /root/.kube
        cp /etc/kubernetes/admin.conf /root/.kube/config
        chown root:root /root/.kube/config

    - name: Create kube config for {{ ansible_user }}
      become_user: "{{ ansible_user }}"
      shell: |
        mkdir -p $HOME/.kube
        sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
      args:
        creates: "~/.kube/config"

    - name: Install Flannel CNI
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      args:
        creates: /etc/cni/net.d/10-flannel.conflist
