# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ .Values.replicas.frontend | default "1" }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}
        resources:
          limits:
            cpu: {{ .Values.resources.frontend.limits.cpu }}
            memory: {{ .Values.resources.frontend.limits.memory }}
          requests:
            cpu: {{ .Values.resources.frontend.requests.cpu }}
            memory: {{ .Values.resources.frontend.requests.memory }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
